version: "3.8"

services:
  api:
    networks:
      - red-mysql
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
  db:
    image: mysql:8.3.0
    networks:
      - red-mysql
    environment:
      MYSQL_DATABASE: 'devops'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'santi2001'
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h db -u root -p santi2001" ]
      timeout: 20s
      retries: 10
    ##ports:
      ##- "3308:3308"
    volumes:
      - db-data:/var/lib/mysql
      - ./base_de_datos.sql:/docker-entrypoint-initdb.d/base_de_datos.sql
networks:
  red-mysql:
volumes:
  db-data:
