version: '3.8'
services:
  app:
    container_name: devops-api
    build:
      context: .
      dockerfile: Dockerfile
    command: ["java", "-Ddebug", "-jar", "DevopsAPI-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/devops?useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=santi2001
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - app-network
  db:
    container_name: postgres
    image: postgres:13
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=santi2001
      - POSTGRES_DB=devops
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
