vversion: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devops
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: santi2001
    depends_on:
      db:
        condition: service_healthy
    networks:
      - red-mysql

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: santi2001
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --password=santi2001" ]
      interval: 10s
      timeout: 20s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
      - ./base_de_datos.sql:/docker-entrypoint-initdb.d/base_de_datos.sql
    networks:
      - red-mysql

networks:
  red-mysql:

volumes:
  db-data:
