version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'devops'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'santi2001'
      MYSQL_ROOT_PASSWORD: 'santi2001'
    ports:
      - "3306:3306"
