name: Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push the Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 --push .

    - name: Run tests
      run: |
        docker run --rm --name my-test-container -it ubuntu:latest /bin/bash -c "echo 'Hello World!'"

    - name: Deploy to production
      run: |
        docker run --rm --name my-production-container -it ubuntu:latest /bin/bash -c "echo 'Deployed to production!'"

    - name: Update the database
      run: |
        docker run --rm --name my-database-container -it ubuntu:latest /bin/bash -c "echo 'Updated the database!'"
