name: CI Pipeline
on: [push, pull_request]

jobs:
  deploy-dev:
    environment:
      name: desarollo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Base de datos pruebas
        working-directory: src/test/database/
        run: docker compose up -d

      - name: Pruebas
        run: mvn test

  deploy-staging:
    needs: deploy-dev
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Base de datos pruebas
        working-directory: src/test/database/
        run: docker compose up -d

      - name: Pruebas
        run: mvn test

  deploy-prod:
    needs: deploy-staging
    environment:
      name: produccion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Base de datos pruebas
        working-directory: src/test/database/
        run: docker compose up -d

      - name: Pruebas
        run: mvn test
