name: CI Pipeline
on: [push, pull_request]

jobs:
  deploy-dev:
    environment:
      name: desarollo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Base de datos pruebas
        working-directory: src/test/database/
        run: docker compose up -d

      - name: Pruebas
        run: mvn test

  deploy-staging:
    needs: deploy-dev
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Base de datos pruebas
        working-directory: src/test/database/
        run: docker compose up -d

      - name: Pruebas
        run: mvn test

  deploy-prod:
    needs: deploy-staging
    environment:
      name: produccion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Base de datos pruebas
        working-directory: src/test/database/
        run: docker compose up -d

      - name: Pruebas
        run: mvn test
      
      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          # Instala la CLI de EB y zip, necesarios para el despliegue.
          pip install awsebcli --upgrade
          sudo apt-get install zip
          # Empaqueta tu aplicación. Ajusta este comando según la estructura de tu proyecto.
          zip -r my-application.zip . -x "*.git*" "tests/*" "ci/*"
          # Inicializa el directorio con la configuración de EB. Asegúrate de estar en el directorio raíz de tu proyecto.
          eb init nombre-de-tu-aplicacion -r $AWS_DEFAULT_REGION -p plataforma-de-ejecucion
          # Despliega tu aplicación. Asegúrate de reemplazar 'nombre-de-tu-aplicacion-environment' con el nombre de tu entorno.
          eb deploy nombre-de-tu-aplicacion-environment
