name: CI Pipeline
on: [push, pull_request]

jobs:
  deploy-dev:
    environment:
      name: desarollo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Base de datos pruebas
        working-directory: src/test/database/
        run: docker compose up -d

      - name: Pruebas
        run: mvn test

  deploy-staging:
    needs: deploy-dev
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Base de datos pruebas
        working-directory: src/test/database/
        run: docker compose up -d

      - name: Pruebas
        run: mvn test

  deploy-prod:
    needs: deploy-staging
    environment:
      name: produccion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Base de datos pruebas
        working-directory: src/test/database/
        run: docker compose up -d

      - name: Pruebas
        run: mvn test

      - name: Terraform PROD Deployment

        on:
          push:
            branches:
              - rama2
          workflow_dispatch:
            branches:
              - rama2

        permissions:
          contents: read
          issues: write
      - jobs:
        gcp-deploy:
          runs-on: ubuntu-latest
          steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v3.0.0
              with:
                fetch-depth: 0

            - id: "auth"
              name: "Authenticate to Google Cloud"
              uses: "google-github-actions/auth@v1"
              with:
                credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
                create_credentials_file: true
                export_environment_variables: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7
      - name: Terraform init and validate
        run: |
          terraform init

      - name: Terraform plan
        run: |
          terraform plan