name: CI Pipeline

on:
  push:
    branches:
      - rama2
  pull_request:
    branches:
      - rama2
  workflow_dispatch:

jobs:
  terraform-prod-deployment:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7

      - name: Terraform init and validate
        run: |
          terraform init
          terraform validate

      - name: Terraform plan
        run: terraform plan
